version: '3.9'
services:
  claim:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run dev
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
networks:
  default:
    driver: bridge

